# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os

import pytest
from pytest_mock import MockerFixture

from wptgen.config import Config
from wptgen.llm import GeminiClient, OpenAIClient, get_llm_client


@pytest.fixture
def gemini_config() -> Config:
  """Provides a valid Gemini configuration."""
  return Config(
    provider='gemini',
    model='gemini-3-pro-preview',
    api_key='mock-gemini-key',
    wpt_path=os.path.join('..', 'wpt'),
  )


@pytest.fixture
def openai_config() -> Config:
  """Provides a valid OpenAI configuration."""
  return Config(
    provider='openai', model='gpt-5.2-high', api_key='mock-openai-key', wpt_path='dummy'
  )


def test_get_llm_client_gemini(mocker: MockerFixture, gemini_config: Config) -> None:
  """Test that the factory returns a GeminiClient when configured for Gemini."""
  # Prevent the actual SDK from initializing
  mocker.patch('wptgen.llm.genai.Client')

  client = get_llm_client(gemini_config)
  assert isinstance(client, GeminiClient)
  assert client.model == 'gemini-3-pro-preview'


def test_get_llm_client_openai(mocker: MockerFixture, openai_config: Config) -> None:
  """Test that the factory returns an OpenAIClient when configured for OpenAI."""
  # Prevent the actual SDK from initializing
  mocker.patch('wptgen.llm.OpenAI')

  client = get_llm_client(openai_config)
  assert isinstance(client, OpenAIClient)
  assert client.model == 'gpt-5.2-high'


def test_get_llm_client_unsupported_provider() -> None:
  """Test that the factory raises an error for unknown providers."""
  bad_config = Config(
    provider='otherllm', model='coolmodel-5', api_key='mock-key', wpt_path='dummy'
  )
  with pytest.raises(ValueError, match='Unsupported provider: otherllm'):
    get_llm_client(bad_config)


def test_gemini_generate_content(mocker: MockerFixture, gemini_config: Config) -> None:
  """Test that GeminiClient correctly maps to the Google GenAI SDK."""
  # Arrange: Mock the Client class and its deep method chain
  mock_client_class = mocker.patch('wptgen.llm.genai.Client')
  mock_instance = mock_client_class.return_value

  # Create a mock response object that has a `.text` property
  mock_response = mocker.MagicMock()
  mock_response.text = 'Generated by mock Gemini'
  mock_instance.models.generate_content.return_value = mock_response

  client = GeminiClient(api_key=gemini_config.api_key, model=gemini_config.model)

  result = client.generate_content(prompt='Test prompt', system_instruction='Test instruction')

  assert result == 'Generated by mock Gemini'
  mock_client_class.assert_called_once_with(api_key='mock-gemini-key')

  # Verify the internal SDK method was called with the correct model and prompt
  call_kwargs = mock_instance.models.generate_content.call_args.kwargs
  assert call_kwargs['model'] == 'gemini-3-pro-preview'
  assert call_kwargs['contents'] == 'Test prompt'
  assert call_kwargs['config'].system_instruction == 'Test instruction'


def test_gemini_count_tokens(mocker: MockerFixture, gemini_config: Config) -> None:
  """Test that GeminiClient correctly maps token counting."""
  mock_client_class = mocker.patch('wptgen.llm.genai.Client')
  mock_instance = mock_client_class.return_value

  # Mock the token response
  mock_response = mocker.MagicMock()
  mock_response.total_tokens = 42
  mock_instance.models.count_tokens.return_value = mock_response

  client = GeminiClient(api_key=gemini_config.api_key, model=gemini_config.model)
  token_count = client.count_tokens('Hello world')

  assert token_count == 42
  mock_instance.models.count_tokens.assert_called_once_with(
    model='gemini-3-pro-preview', contents='Hello world'
  )


def test_openai_generate_content(mocker: MockerFixture, openai_config: Config) -> None:
  """Test that OpenAIClient correctly maps to the OpenAI SDK."""
  # Arrange: Mock the OpenAI class and its deep method chain
  mock_openai_class = mocker.patch('wptgen.llm.OpenAI')
  mock_instance = mock_openai_class.return_value

  # Simulate OpenAI's deep response structure: response.choices[0].message.content
  mock_message = mocker.MagicMock()
  mock_message.content = 'Generated by mock OpenAI'
  mock_choice = mocker.MagicMock()
  mock_choice.message = mock_message
  mock_response = mocker.MagicMock()
  mock_response.choices = [mock_choice]

  mock_instance.chat.completions.create.return_value = mock_response

  client = OpenAIClient(api_key=openai_config.api_key, model=openai_config.model)

  result = client.generate_content(prompt='Test prompt', system_instruction='Test instruction')

  assert result == 'Generated by mock OpenAI'
  mock_openai_class.assert_called_once_with(api_key='mock-openai-key')

  # Verify the payload structure sent to OpenAI
  mock_instance.chat.completions.create.assert_called_once_with(
    model='gpt-5.2-high',
    messages=[
      {'role': 'system', 'content': 'Test instruction'},
      {'role': 'user', 'content': 'Test prompt'},
    ],
  )


def test_gemini_prompt_exceeds_limit(mocker: MockerFixture, gemini_config: Config) -> None:
  """Test token limit checking for Gemini."""
  mock_client_class = mocker.patch('wptgen.llm.genai.Client')
  mock_instance = mock_client_class.return_value

  # Mock count_tokens
  mock_count_response = mocker.MagicMock()
  mock_count_response.total_tokens = 500
  mock_instance.models.count_tokens.return_value = mock_count_response

  # Mock models.get
  mock_model_info = mocker.MagicMock()
  mock_model_info.input_token_limit = 1000
  mock_instance.models.get.return_value = mock_model_info

  client = GeminiClient(api_key=gemini_config.api_key, model=gemini_config.model)

  # Case 1: Under limit
  assert client.prompt_exceeds_input_token_limit('some prompt') is False

  # Case 2: Over limit
  mock_count_response.total_tokens = 1500
  assert client.prompt_exceeds_input_token_limit('huge prompt') is True

  # Case 3: No limit specified in model info (fallback)
  mock_model_info.input_token_limit = None
  mock_count_response.total_tokens = 500000
  assert client.prompt_exceeds_input_token_limit('prompt') is False
  mock_count_response.total_tokens = 1500000
  assert client.prompt_exceeds_input_token_limit('huge prompt') is True


def test_openai_count_tokens(mocker: MockerFixture, openai_config: Config) -> None:
  """Test that OpenAIClient correctly maps token counting using tiktoken."""
  mocker.patch('wptgen.llm.OpenAI')
  client = OpenAIClient(api_key=openai_config.api_key, model=openai_config.model)

  # Test with a known string. "Hello, world!" is 4 tokens in cl100k_base:
  # ['Hello', ',', ' world', '!']
  token_count = client.count_tokens('Hello, world!')
  assert token_count == 4


def test_openai_prompt_exceeds_limit(mocker: MockerFixture, openai_config: Config) -> None:
  """Test token limit checking for OpenAI."""
  mocker.patch('wptgen.llm.OpenAI')
  client = OpenAIClient(api_key=openai_config.api_key, model=openai_config.model)

  # Case 1: Under limit (400k)
  # A short prompt should definitely be under the 400k limit
  assert client.prompt_exceeds_input_token_limit('short prompt') is False

  # Case 2: Over limit
  # Generate a very large prompt that exceeds 400k tokens.
  # "a " is usually 1 token. 400,001 "a "s should exceed the limit.
  huge_prompt = 'a ' * 400001
  assert client.prompt_exceeds_input_token_limit(huge_prompt) is True
