import pytest

from wptgen.config import Config
from wptgen.llm import GeminiClient, OpenAIClient, get_llm_client


@pytest.fixture
def gemini_config():
  """Provides a valid Gemini configuration."""
  return Config(
    provider='gemini',
    model='gemini-3-pro-preview',
    api_key='mock-gemini-key',
    wpt_path='../wpt',
  )

@pytest.fixture
def openai_config():
  """Provides a valid OpenAI configuration."""
  return Config(
    provider='openai',
    model='gpt-5.2-high',
    api_key='mock-openai-key',
    wpt_path='../wpt'
  )

def test_get_llm_client_gemini(mocker, gemini_config):
  """Test that the factory returns a GeminiClient when configured for Gemini."""
  # Prevent the actual SDK from initializing
  mocker.patch('wptgen.llm.genai.Client')

  client = get_llm_client(gemini_config)
  assert isinstance(client, GeminiClient)
  assert client.model == 'gemini-3-pro-preview'

def test_get_llm_client_openai(mocker, openai_config):
  """Test that the factory returns an OpenAIClient when configured for OpenAI."""
  # Prevent the actual SDK from initializing
  mocker.patch('wptgen.llm.OpenAI')

  client = get_llm_client(openai_config)
  assert isinstance(client, OpenAIClient)
  assert client.model == 'gpt-5.2-high'

def test_get_llm_client_unsupported_provider():
  """Test that the factory raises an error for unknown providers."""
  bad_config = Config(
    provider='otherllm',
    model='coolmodel-5',
    api_key='mock-key',
    wpt_path='../wpt'
  )
  with pytest.raises(ValueError, match='Unsupported provider: otherllm'):
    get_llm_client(bad_config)

def test_gemini_generate_content(mocker, gemini_config):
  """Test that GeminiClient correctly maps to the Google GenAI SDK."""
  # Arrange: Mock the Client class and its deep method chain
  mock_client_class = mocker.patch('wptgen.llm.genai.Client')
  mock_instance = mock_client_class.return_value

  # Create a mock response object that has a `.text` property
  mock_response = mocker.MagicMock()
  mock_response.text = 'Generated by mock Gemini'
  mock_instance.models.generate_content.return_value = mock_response

  client = GeminiClient(api_key=gemini_config.api_key, model=gemini_config.model)

  result = client.generate_content(prompt='Test prompt', system_instruction='Test instruction')

  assert result == 'Generated by mock Gemini'
  mock_client_class.assert_called_once_with(api_key='mock-gemini-key')

  # Verify the internal SDK method was called with the correct model and prompt
  call_kwargs = mock_instance.models.generate_content.call_args.kwargs
  assert call_kwargs['model'] == 'gemini-3-pro-preview'
  assert call_kwargs['contents'] == 'Test prompt'
  assert call_kwargs['config'].system_instruction == 'Test instruction'

def test_gemini_count_tokens(mocker, gemini_config):
  """Test that GeminiClient correctly maps token counting."""
  mock_client_class = mocker.patch('wptgen.llm.genai.Client')
  mock_instance = mock_client_class.return_value

  # Mock the token response
  mock_response = mocker.MagicMock()
  mock_response.total_tokens = 42
  mock_instance.models.count_tokens.return_value = mock_response

  client = GeminiClient(api_key=gemini_config.api_key, model=gemini_config.model)
  token_count = client.count_tokens('Hello world')

  assert token_count == 42
  mock_instance.models.count_tokens.assert_called_once_with(
    model='gemini-3-pro-preview',
    contents='Hello world'
  )

def test_openai_generate_content(mocker, openai_config):
  """Test that OpenAIClient correctly maps to the OpenAI SDK."""
  # Arrange: Mock the OpenAI class and its deep method chain
  mock_openai_class = mocker.patch('wptgen.llm.OpenAI')
  mock_instance = mock_openai_class.return_value

  # Simulate OpenAI's deep response structure: response.choices[0].message.content
  mock_message = mocker.MagicMock()
  mock_message.content = 'Generated by mock OpenAI'
  mock_choice = mocker.MagicMock()
  mock_choice.message = mock_message
  mock_response = mocker.MagicMock()
  mock_response.choices = [mock_choice]

  mock_instance.chat.completions.create.return_value = mock_response

  client = OpenAIClient(api_key=openai_config.api_key, model=openai_config.model)

  result = client.generate_content(prompt='Test prompt', system_instruction='Test instruction')

  assert result == 'Generated by mock OpenAI'
  mock_openai_class.assert_called_once_with(api_key='mock-openai-key')

  # Verify the payload structure sent to OpenAI
  mock_instance.chat.completions.create.assert_called_once_with(
    model='gpt-5.2-high',
    messages=[
      {'role': 'system', 'content': 'Test instruction'},
      {'role': 'user', 'content': 'Test prompt'}
    ]
  )
